### ISSUE TITLE
Dokumenter valget af multi og trilatererings metode, samt udgangspunktet.

### ISSUE THREAD

**Issue by dkalaxdk** [P8-Team/Report#15]
Dokumentationen for valget skal også laves på en måde hvor vi har den internt.

**Comment by TrineHolmager** [comment]
se related work under locating. Det er indsat under overskriften "valg af specifik metode starter her," som blot er lavet for at det er nemt at se hvor det står :)

Jeg ønsker generel feedback, fx både kommentarer på om det er dækkende nok for valget af specifik metode, tegnsætning mm.

**Comment by LauJosefsen** [comment]
Synes det er fint initierende afsnit, rettelserne er mest bare småting. :)
