### ISSUE TITLE
Definer approach for classification

### ISSUE THREAD

**Issue by dkalaxdk** [P8-Team/Report#18]
- [x] Hvordan behandler vi data?
- [x] Hvilke data typer arbejdes der med?

Dokumenter de ovenstående, både ifht til rapport, men også internt.

**Comment by soenderby** [comment]
Data behandles af funktionerne der filtrerer og aggregere wifi frames.
Herefter skal der foretages feature selection og extraction ved brug af tsfresh.
Dette kræver at wifi frames kan laves til Pandas dataframes med et format der kan bruges af tsfresh (dokumenteret [her](https://tsfresh.readthedocs.io/en/latest/text/data_formats.html)).
For at gøre dette er planen at lave en *to_dataframe* metode på wifi_frame klassen, samt de to klasser den består af (*frame_control_information* og *wlan_radio_information*)

Herefter gives de resulterende dataframes til tsfresh for feature selection og extraction, hvorefter de resulterende features gives til classifieren.
