### ISSUE TITLE
Dataopsamling

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/Report#26]
Hvordan har vi gjort det (tshark, opstillinger)?

**Comment by Kaliahh** [comment]
- [x] Contains no irrelevant information. 
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The section uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.

**Comment by LauJosefsen** [comment]
- [x] Contains no irrelevant information. 
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The section uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.

Synes ikke jeg kan sætte flere bokse, men det fremgår af kommentarerne hvorfor. Ellers fint afsnit ❤️
