### ISSUE TITLE
Beskriv den data vi arbejder med i dataopsamlingen

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/Report#27]
Hvordan ser dataen ud (måske en tabel)? Beskriv relevante detaljer om WiFi (monitor mode, promiscious mode, kanaler)

Tag eventuelt dele fra WiFi afsnittet i rapporten

**Comment by LauJosefsen** [comment]
Vil gerne have øjne i data_collection2.tex

Med fokus på om det jeg forklarer er relevant og giver mening, og evt grammatiske ting. Jeg har prøvet at nævne de irellevante ting meget kort, bare for at nævne alt der er i en WiFi frame.

**Comment by dkalaxdk** [comment]
I hath given the feedback which was requested.

**Comment by soenderby** [comment]
- [ ] Contains no irrelevant information. 
- [x] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section.
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The section uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.

Vi har diskuteret nogle ændringer i indholdet, jeg har sat kommentarer på hvordan dette kan håndteres.

**Comment by dkalaxdk** [comment]
- [ ] Contains no irrelevant information. 
- [x] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The section uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
