### ISSUE TITLE
Databehandling (træning)

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/Report#28]
Beskriv hvad der bliver gjort ved den data vi får ind, så vi kan træne på det. 

Beskriv tsfresh's magi i den omfang det giver mening for rapporten (Hvad gør det, ikke hvordan)

Beskriv hvordan dataen ser ud når det bliver givet som input til træningen

Hvad får vi ind? Hvad gør tsfresh ved det? Hvad får vi ud?

**Comment by soenderby** [comment]
Har indsat tabeller der viser data, og korte noter der outliner pointerne der hører til. 
Det burde danne et overblik over hvad afsnittet kommer til at indeholde.
Jeg vil gerne have feedback på om der er nogle pointer der skal tilføjes, fjernes, reduceres eller uddybes, samt feedback på rækkefølgen af pointer.

**Comment by soenderby** [comment]
Full review this time please

**Comment by Kaliahh** [comment]
- [x] Contains no irrelevant information. 
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The section uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.

Starten er stadigvæk lidt shaky, der er potentielt noget gentagelse og forvirring omkring hvilket komponent afsnittet handler om, men slutningen er der

**Comment by soenderby** [comment]
Hvis der er flere kommentarer, diskuter dem med mig verbalt, da de ellers begynder at kræve lange forklaringer.

**Comment by soenderby** [comment]
The implementation of data processing changed. I have adapted the text
