### ISSUE TITLE
Udarbejd testopstillinger til evalueringen

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/Report#29]
Find ud af hvordan vi skal teste vores produkt. 

Hvor skal det gøres? Hvor mange forskellige opstillinger skal vi have? Er der edge cases?

Hvilken data vil vi gerne have ud af evalueringen? (Så meget som muligt)

**Comment by soenderby** [comment]
Afsnittet indeholder korte beskrivelser af hvad de forskellige tests indebærer og deres formål. Jeg har reviewet disse.

Inden afsnittet skrive mener jeg det vil gavne hvis vi undersøger og diskuterer hvordan vi skal beskrive vores tests.
Pointer der skal undersøges/diskuteres:
 - Er der en standard for hvordan man gør?
 - Skal læseren kunne udføre testen og hvilken information er nødvendig for dette?  

Dette er ikke en fuldendt liste men er ment som et udgangspunkt

**Comment by LauJosefsen** [comment]
Synes overordnet det er meget fint, men har sat et par kommentarer.
