### ISSUE TITLE
Related Work: Opførsel - Skriv punkter sammen

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/Report#7]
Skriv sammen til sammenhængende tekst. 

Præsenter related work på den måde der giver mening for feltet. 

Giv et summary af det related work der er blevet præsenteret.

Afhængig af:
- [x] #5

**Comment by soenderby** [comment]
Reviewed.
Jeg har efterladt nogle kommentarer, men overordnet syntes jeg ikke helt det er struktureret som jeg forventer related work ville være.
